dist: trusty

jobs:
  include: 
    - stage: Dokcer build stage
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t devopscourse .
        - docker images
        - docker tag devopscourse $DOCKER_USERNAME/devopscourse:$TRAVIS_BUILD_NUMBER
        - docker push $DOCKER_USERNAME/devopscourse:$TRAVIS_BUILD_NUMBER
        - docker tag devopscourse $DOCKER_USERNAME/devopscourse
        - docker push $DOCKER_USERNAME/devopscourse:latest